# Generated by Django 4.0.6 on 2022-08-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_alter_quest_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='quest_id',
            new_name='quest',
        ),
        migrations.AddField(
            model_name='submission',
            name='shortlisted',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
