# Generated by Django 4.0.6 on 2022-08-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buetpx', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_title', models.CharField(max_length=500)),
                ('quest_theme', models.CharField(max_length=500)),
                ('quest_description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('reward', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='buetpx.post')),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='buetpx.category')),
            ],
        ),
    ]
