# Generated by Django 4.0.6 on 2022-08-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_alter_quest_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='reward',
            field=models.CharField(max_length=500),
        ),
    ]
