# Generated by Django 4.0.5 on 2022-07-13 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buetpx', '0002_category_gallery_place_tags_useraccount_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='12/12/12', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='locality',
            field=models.CharField(default='exit', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='sublocality',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='buetpx.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='buetpx.useraccount'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='buetpx.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='buetpx.useraccount'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='buetpx.place'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='buetpx.tags'),
        ),
    ]
