# Generated by Django 4.0.5 on 2022-07-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buetpx', '0004_place_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=500)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.URLField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='buetpx.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='buetpx.useraccount')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='buetpx.place')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='buetpx.tags')),
            ],
        ),
    ]
