# Generated by Django 4.0.6 on 2022-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buetpx', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='photo_url',
            field=models.URLField(max_length=1000),
        ),
    ]
